# Generated by Django 4.2.7 on 2023-11-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('task_name', models.CharField(unique=True)),
                ('task_description', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
